title: WASA 2024
description: The 10th International Workshop on Automotive System/Software Architectures
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
keywords: "workshops, automotive, software engineering, software architecture"

# author settings for cc-by, appears in the footer
author: Stefan Kugele, Yanja Dajsuren, and Alessio Bucaioni
pub_year: 2024
github_username: stefankugele


