title: WASA 2025
description: The 11th International Workshop on Automotive System/Software Architectures
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
keywords: "workshops, automotive, software engineering, software architecture"

# author settings for cc-by, appears in the footer
author: Stefan Kugele, Yanja Dajsuren, Alessio Bucaioni, and Jasmin Jahić
pub_year: 2025
github_username: stefankugele


